### ISSUE TITLE
listen for "normal" messages

### ISSUE THREAD

**Issue by japel** [seneca-contrib/seneca-amqp-transport#28]
Hey there,
is there a way to listen to messages that were not made with a seneca-amqp-transport client?

Thanks in advance

japel

**Comment by nfantone** [comment]
Hi, @japel.

Of course there is. Apart from the payload's format, there's nothing special about messages created by the plugin. Assuming you left defaults untouched, just route one to `seneca.topic` and the desired routing key and you're good to go.

To see what the actual payload should look like, I'd recommend running a simple script with a `seneca.act` on it. Make sure there's no listener declared for that act. That way, your script will timeout, but will leave a message on the actual queue. Retrieve that message and inspect the payload.

If, for some reason, you cannot modify the original payload to accommodate to what the plugin needs, then the only other way would be to create some sort of adapter middleware that works the magic.

**Comment by japel** [comment]
@nfantone thanks for your answer!
I've found this:
```javascript
{ max: 100,
  min: 25,
  role: 'create',
  'transport$': 
   { track: [ 'nmcupaucu2lv/1463040763366/30554/-' ],
     origin: 'nmcupaucu2lv/1463040763366/30554/-',
     time: { client_sent: 1463045444299 } },
  'ungate$': true,
  'tx$': '72q3af4txbxn',
  'plugin$': { name: 'seneca-amqp-transport', tag: undefined },
  'fatal$': true,
  'default$': undefined,
  'meta$': 
   { id: 'jhtw9g9nddrh/72q3af4txbxn',
     tx: '72q3af4txbxn',
     start: 1463045444301,
     pattern: 'role:create',
     action: '(uvp5zxz28yhd)',
     entry: true,
     chain: [],
     sync: true } }
```

as output of your standard client/listener example... If I understand you right the messages produced by non-seneca-apps should have a similar format to be able to work with this plugin?

**Comment by nfantone** [comment]
Exactly. Be aware that different acts produce different payloads. For instance, using `entity.save`, yields something like: 

```json
{"id":"frqhyqedynqs/evwnp7ser6xk","kind":"act","origin":"nu4jvdp64csr/1462894514511/22295/-","track":["nu4jvdp64csr/1462894514511/22295/-"],"time":{"client_sent":1462894515162},"act":{"cmd":"save","role":"entity","ent":{"entity$":"-/tfo/user","accountNo":"ACC1","email":"fake@foobar.com"},"name":"user","base":"tfo"},"sync":true}
```

However, most of those fields are internally generated and _not_ mandatory. Unfortunately, there's no easy way to tell which ones. The actual content is transport independent, and thus, not generated by this plugin, but by Seneca itself.

Try experimenting a bit and see if the listener executes fine by pushing different payloads.

**Comment by japel** [comment]
Alright, I'll take a look at it.
Thank you very much for your help!

**Comment by mihaidma** [comment]
I caught messages with netcat started in server mode: `nc -l 2345`. It opens a server that displays everything received, you just point your act service to that port

**Comment by japel** [comment]
@mihaidma thanks for that insight... that helps

**Comment by nfantone** [comment]
@japel Feel free to close the issue if you have no further questions.
