### ISSUE TITLE
Unit tests and coverage

### ISSUE THREAD

**Issue by nfantone** [seneca-contrib/seneca-amqp-transport#31]
Before releasing 1.0.0, it would be nice to have basic functionality tested using Mocha and a [coverage report](https://codecov.io)

- [x] Write unit test for `amqp-util.js`
- [x] Mock out amqplib stuff.
- [x] Write unit test for `listener.js`.
- [x] Write unit test for `client.js`.

@disintegrator Could you give a hand here, if you are available?

**Comment by chefArchitect** [comment]
@nfantone I have already started writing Mocha unit and functional tests that will cover the full module.  Will create an initial PR tomorrow.

**Comment by nfantone** [comment]
Hey, @chefArchitect, that's awesome news! Thank you very much. Looking forward to that PR.

**Comment by nfantone** [comment]
Work began in #34

**Comment by nfantone** [comment]
Merged!
