### ISSUE TITLE
"Round Robin" load balancing

### ISSUE THREAD

**Issue by tvedtorama** [seneca-contrib/seneca-amqp-transport#32]
Hi,

I see there's another question on queue broadcast, but what if I just want to "randomly" distribute requests to multiple, equal, micro services?  It seems that this is supported in the queue-world, but from what I understand in your documentation, every seneca listener will create its own queue.

I would still want the result of the operation back in my callback, so it's not "fire and forget". 

Does this make sense with seneca, and/or is it already possible?

Multiple processors would make sense from a scaling and performance perspective.

**Comment by tvedtorama** [comment]
I fired up the examples, using the following syntax to run a local docker Rabbit MQ:

    docker run -d --hostname my-rabbit --name some-rabbit -p 8080:15672 -p 5672:5672 rabbitmq:3-management

... and found that "round robin" distribution is indeed what is used.  Pardon my ignorance.

**Comment by nfantone** [comment]
Nothing to forgive here.

But that's correct. If you spawn multiple microservices, what you'll get is multiple consumers on the same queue. The broker (RabbitMQ, zmq, Kafka, etc.) will handle the balancing between them.
