### ISSUE TITLE
Random issue with the transport

### ISSUE THREAD

**Issue by OriginalEXE** [seneca-contrib/seneca-amqp-transport#33]
Apologies for the terrible issue title, I did not know how to describe it.

So I'm running into an issue which (I assume based on the circumstances) is caused by this transport plugin.

Basically, I am building an API using seneca and I have three services for now, web-server, users-read and users-write. web-server is the express server, users-read performs only read operations for the API, and users-write only the writing ones.

The issue I am running into is that the call to a specific seneca patterns works only on my first request, and if I re-request it again (with nothing changed) it times out. Specifically, it's [this line](https://github.com/OriginalEXE/Seneca-Playground/blob/master/modding-api-users-write/src/seneca-plugins/users.api.validate.js#L114).

So what it does is calls the 'users-read' service to check if the username passed via post is already present in the database. This works great the first time, but the second time I just get a timeout here (and the service which is supposed to handle this request, defined [here](https://github.com/OriginalEXE/Seneca-Playground/blob/master/modding-api-users-read/src/seneca-plugins/users.api.query-factory.js), never does).

Now comes the crazy part, if I remove the username validation and only validate email (which does the same thing, only with email (but the pattern is the same), it works every time and I get no timeout issues. The only difference is that in username validation request, the queryParams object sent has a username property, while when validating email it's the email property that the object has.

You can run my example via docker compose. I know it's a lot of code and I wouldn't be posting this here if I was not desparate. I think this is transport related because if I move the users.api.query-factory.js plugin to my users-write service (so that the pattern is matched locally and it doesn't have to look for it via transport), it works without issues.

Any help will be greatly appreciated, thanks!

P.S. I tried downgrading seneca to 1.3.0 and it did not help.

**Comment by OriginalEXE** [comment]
Ok I just realized that the behavior is quite random, sometimes it works for the first time, sometimes it doesn't work at all (but email validation works), sometimes neither works.

What I'm thinking this might be related to is that the process involves three services instead of just two (like my get request, which always works). Could that be causing some kind of issue?

So the GET request to `http://localhost:3000/api/v1/users/` goes like this:
web-server->users-read->web-server

and the POST request goes like this:
web-server->users-write->users-read->users-write->web-server

I don't know if this matters, I'm just out of ideas.

**Comment by nfantone** [comment]
@OriginalEXE I can smell your desperation. Unfortunately, I'm finding it a bit hard to help you out on current conditions. Could you isolate the issue a little more? Or provide a detailed guide on how to reproduce it? I'm not quite sure on _what_ the problem is, really.

**Comment by OriginalEXE** [comment]
I tried recreating a simpler scenario but could not reproduce the issue, sorry.

So here's the guide on how to reproduce the issue I am having:

1.) Clone my repo
2.) In the microservices directory, run docker-compose build
3.) When it builds, run it with docker-compose up
4.) Wait about 10-15 seconds for it to start properly (some services will restart as they are trying to connect before the rabbitmq properly starts and they are failing)
5.) Once all services properly start, test that things are working by visiting `http://localhost:3000/api/v1/users/` in your browser (you should get `{"data":[]}` as a response because there are no users in the database)
6.) Now try sending a POST request with this body:
```
{
    "username": "Username",
    "email"   : "someemail@gmail.com"
}
```
I use Postman for this, don't forget to include `Content-Type: application/json` header

Once you send the POST request, it will reach [this line](https://github.com/OriginalEXE/Seneca-Playground/blob/master/modding-api-users-write/src/seneca-plugins/users.api.validate.js#L114) and then time out because the handler that should respond to that pattern ([defined here](https://github.com/OriginalEXE/Seneca-Playground/blob/master/modding-api-users-read/src/seneca-plugins/users.api.query-factory.js)) never actually receives the request. Why, I am not sure, because if you look at the pattern it should definitely respond.

For debugging, you can change any code and the pm2 should detect it and restart the service. Note that once the time out happens, I found I had to stop the containers and restart them for things to get to the working state again.

Again, I know I am asking a lot here, but I'm kinda desperate, that's the only reason I decided to seek for help.

**Comment by nfantone** [comment]
@OriginalEXE Ok. Give me a couple hours and I'll run your example.

**Comment by nfantone** [comment]
@OriginalEXE Very sorry to ask this, but couldn't you provide me with a plain `node some-script.js` kinda scenario? I don't have a Docker installation on my current laptop and, being on MacOSX, I need to download a trillion different things to get this working.

If not, you'll have to wait 'till I got some more free time during the weekend to set things up for you.

**Comment by OriginalEXE** [comment]
Of course, that's the least I can do. I'll set it up and let you know, I'll try to simplify things as much as I can.

**Comment by OriginalEXE** [comment]
Ok I have created a minimal environment that can reproduce the bug.

Repo here: https://github.com/OriginalEXE/Seneca-AMQP-Bug-Environment

How to run it:
1.) [Install and run RabbitMQ](https://www.rabbitmq.com/download.html) (default settings)
2.) Install pm2 globally (`npm install -g pm2`)
3.) In each of these three directories, run `pm2 starts ./pm2dev.json
4.) Use `pm2 logs` in an of the service folder to display logs
5.) Send `POST` request to `http://localhost:3000/api/v1/users` with the raw body of
```
{
    "username": "Username",
    "email"   : "email@gmail.com"
}
```
and the `Content-Type` `application/json` header
6.) Watch as the timeout happens [here](https://github.com/OriginalEXE/Seneca-AMQP-Bug-Environment/blob/master/api-users-write/src/seneca-plugins/users.api.validate.js#L19) even though the signature should match [this](https://github.com/OriginalEXE/Seneca-AMQP-Bug-Environment/blob/master/api-users-read/src/seneca-plugins/users.api.query-factory.js) plugin (that never receives request).

Note that it might work the first time you send the POST request, it's quite random.

**Comment by nfantone** [comment]
@OriginalEXE Ok, I tested you project. And I think I've found at least _one_ issue.

You have two microservices declaring listeners and clients _with the same pin_ (`role:api`). That means, two listeners consuming messages from the same queue.

<img width="612" alt="screen shot 2016-06-04 at 11 19 25 pm" src="https://cloud.githubusercontent.com/assets/476069/15803256/e2424c90-2aaa-11e6-8619-a783b4eef96a.png">

While totally valid, that generates a race condition if the listeners are performing different tasks. Whichever consumer draws a message first, will get to process it. After that first consumption, messages will be delivered in [a round-robin fashion](https://www.rabbitmq.com/consumer-priority.html). I believe that's the reason behind the random behaviour you are getting.

So the solution would be to set different pins to listeners doing different stuff. Maybe `role:api,cmd:write` and `role:api,cmd:read`?

----

On a side note, and just for future reference, you _could_ have presented this scenario in a **much simpler** way:

- There's absolutely no need for pm2. Just `node src/index.js`.
- RabbitMQ installation is also not a requirement. You could have used the official test server at dev.rabbitmq.com. Or create a free [CloudAMQP server](https://customer.cloudamqp.com/instance/create?plan%3Dlemur) just to test your project, which is what I did.

I'm commenting this so you could, perhaps, take this tools into account next time you need to present this to someone else seeking help.

**Comment by OriginalEXE** [comment]
Hi,

thanks again for taking the time to help! You are right, that's exactly what was causing the issue.

I have a question though, does that mean I need to spawn multiple clients with pins matching those of the listeners of the services I will use? I thought there was a way to just specify "for any message of the pattern role:api look for services on url x", but I'm guessing that's not doable. It's not a problem, just asking if that's the way to go then.

P.S. I'm aware pm2 was not needed, I just use it for reloading my services on code change so I kinda assumed you will want to do the same while debugging my code. Thanks for the rabbitmq advice though, I'm new to it so I had no idea it's that easy to get a dev server.

**Comment by nfantone** [comment]
> thanks again for taking the time to help! You are right, that's exactly what was causing the issue.

I'm glad I could be of help!

> does that mean I need to spawn multiple clients with pins matching those of the listeners of the services I will use?

If by "spawn multiple clients" you mean having multiple process running at once, then no, you don't need to do that. You can declare more than one client in a single microservice. Otherwise, the answer is yes.

TBH, pins in the client side are _not entirely_ logical. We could do without those. The only thing that's actually necessary is the act pattern. This could be a field of research in a not-so-distant future. Seneca itself is planning on [deprecating pins entirely](http://senecajs.org/roadmap.html#5-0-november-2016).

**Comment by OriginalEXE** [comment]
Yeah sorry for wording it poorly, I meant declaring multiple client() connections per service. I agree that it's not very logical, looking forward to simplifying it in the future.

Thanks again!
