### ISSUE TITLE
Debug/test messages?

### ISSUE THREAD

**Issue by jofan** [seneca-contrib/seneca-amqp-transport#51]
Wonder if someone could help me understand how I can test the transport by sending messages to rabbitMQ from the outside?

For example, if I have the following, what would I need in the payload to send a Seneca "cmd":

```
rabbitmqadmin publish exchange='seneca.topic' routing_key='role.demo' payload=?
```

**Comment by nfantone** [comment]
@jofan This has been answered before. You can take a look at #28. Follow the thread: it has some advice on how to proceed to achieve what you want. If you need further assistance, write me back here.

**Comment by jofan** [comment]
@nfantone Thank you, I did see that message after my post. I haven't been able to send a message even with the output from inspecting seneca.act. I'll keep looking into it.

**Comment by nfantone** [comment]
@jofan What exactly is it that you are struggling with? Maybe I can give you some pointers?
